table fact_experiment_exposure
	lineageTag: 5006ebe0-9487-4a77-9b35-6a5f8a50abc3

	measure Users = ```
			DISTINCTCOUNT(fact_experiment_exposure[user_id]) 
			```
		formatString: 0
		lineageTag: 024b7863-4671-4613-942d-586ad051bd1d

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: e2e91cab-ffbb-42fc-bafe-233838e7d884
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column experiment_group
		dataType: string
		lineageTag: 49ecf7e9-fd74-4df2-9ae6-00175d6565ee
		summarizeBy: none
		sourceColumn: experiment_group

		annotation SummarizationSetBy = Automatic

	column exposure_time
		dataType: dateTime
		formatString: Long Date
		lineageTag: f4aee7c0-b4e4-4051-bed8-688bd87d2e5c
		summarizeBy: none
		sourceColumn: exposure_time

		variation Variation
			isDefault
			relationship: 10826cff-5558-4d89-a335-95cf40ee619c
			defaultHierarchy: LocalDateTable_d409a1b0-5234-4752-8a17-141ae31e765c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_experiment_exposure = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tanis\OneDrive\All_DataSet\google_analytics_ab_testing_50k_events\fact_experiment_exposure.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"user_id", Int64.Type}, {"experiment_group", type text}, {"exposure_time", type date}})
				in
				    #"Change Type"

	annotation PBI_ResultType = Table

